asset/urls.py
from django.urls import path
from asset.views import DeviceAutocomplete
from asset.views import DeviceList, DeviceCreate, DeviceUpdate, DeviceDelete
from asset.views import MaterialList, MaterialCreate, MaterialUpdate, MaterialDelete

app_name = 'asset'

urlpatterns = [
    path('device-autocomplete/', DeviceAutocomplete.as_view(), name='device-autocomplete'),
    path('devices', DeviceList.as_view(), name='devices'),
    path('device/add', DeviceCreate.as_view(), name='add_device'),
    path('device/<int:pk>/', DeviceUpdate.as_view(), name='edit_device'),
    path('device/<int:pk>/delete', DeviceDelete.as_view(), name='delete_device'),
    path('materials', MaterialList.as_view(), name='materials'),
    path('material/add', MaterialCreate.as_view(), name='add_material'),
    path('material/<int:pk>/', MaterialUpdate.as_view(), name='edit_material'),
    path('material/<int:pk>/delete', MaterialDelete.as_view(), name='delete_material'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', views.index, name = 'index'),
    path('stock/', include('stock.urls')),
    path('basic/', include('basic.urls')),
    path('asset/', include('asset.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete

from user.views import UserProfileList, UserProfileCreate, UserProfileUpdate, UserProfileDelete, UserProfileAutocomplete

app_name = 'user'

urlpatterns = [
    path('profiles', UserProfileList.as_view(), name='profiles'),
    path('profile/add', UserProfileCreate.as_view(), name='add_profile'),
    path('profile/<int:pk>/', UserProfileUpdate.as_view(),
         name='edit_profile'),
    path('profile/<int:pk>/delete',
         UserProfileDelete.as_view(),
         name='delete_profile'),
path('employee-autocomplete/', UserProfileAutocomplete.as_view(), name='employee-autocomplete'),
]

asset/models.py
from django.db import models
from django.urls import reverse

from basic.models import CommonInfo, Wordbook, Warehouse


class Device(CommonInfo):
    status_choice = (
        (1, '在库中'),
        (2, '已出库'),
    )
    good_choice = (
        (1, '故障'),
        (5, '良好'),
    )
    brand = models.ForeignKey(Wordbook,
                              blank=True,
                              on_delete=models.SET_NULL,
                              related_name='device_brands',
                              null=True,
                              verbose_name="品牌")
    model = models.ForeignKey(Wordbook,
                              blank=True,
                              on_delete=models.SET_NULL,
                              related_name='device_models',
                              null=True,
                              verbose_name="型号")
    sn = models.CharField(max_length=100, verbose_name="设备编码", db_index=True)
    classification = models.ForeignKey(Wordbook,
                                       blank=True,
                                       on_delete=models.SET_NULL,
                                       related_name='device_classifications',
                                       null=True,
                                       verbose_name="类型")
    good = models.IntegerField(default=5,
                               choices=good_choice,
                               verbose_name="设备状态")
    value = models.DecimalField(default=0,
                                max_digits=10,
                                decimal_places=2,
                                verbose_name="价格")
    asset = models.CharField(max_length=100,
                             blank=True,
                             null=True,
                             verbose_name="资产编码")
    sap = models.CharField(max_length=100,
                           blank=True,
                           null=True,
                           verbose_name="SAP")
    status = models.IntegerField(default=1,
                                 choices=status_choice,
                                 verbose_name="状态")


    def __str__(self):
        return self.brand.name + '/' + self.model.name + '/' + self.sn  # + ' ' + self.category.name

    def get_device_display(self):
        return u'{0}/{1}/{2}'.format(self.brand.name, self.model.name, self.sn)

    def get_type_display(self):
        if self.type:
            return self.type.get_type_display()
        else:
            return ""

    def autocomplateFormate(self):
        return {
            'label': self.name.name + '/' + self.model.name + '/' + self.sn,
            'value': self.id
        }

    def get_absolute_url(self):
        return reverse('asset:edit_device', args=[str(self.id)])

    class Meta:
        verbose_name = '设备表'
        verbose_name_plural = '设备表'


class Material(CommonInfo):
    classification = models.ForeignKey(Wordbook,
                                       blank=True,
                                       on_delete=models.SET_NULL,
                                       related_name='material_classifications',
                                       null=True,
                                       verbose_name="类型")
    name = models.ForeignKey(Wordbook,
                             blank=True,
                             on_delete=models.SET_NULL,
                             related_name='material_names',
                             null=True,
                             verbose_name="名称")
    amount = models.DecimalField(default=0,
                                 max_digits=10,
                                 decimal_places=2,
                                 verbose_name="数量")
    warehouse = models.ForeignKey(Warehouse,
                                  on_delete=models.SET_NULL,
                                  blank=True,
                                  null=True,
                                  verbose_name="所在库房")

    def get_absolute_url(self):
        return reverse('asset:edit_material', args=[str(self.id)])

    class Meta:
        verbose_name = '材料表'
        verbose_name_plural = '材料表'

asset/forms.py
from django import forms
from django.forms import TextInput, Textarea, Select

from dal import autocomplete

from asset.models import Device, Material


class DeviceForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    value = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False, initial=0)
    asset = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    sap = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}), required=False)
    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Device
        fields = ('id', 'classification', 'brand', 'model', 'sn', 'value', 'asset', 'sap', 'good','description')
        widgets = {
            'classification': autocomplete.ModelSelect2(
                        url='basic:wordbook-autocomplete',
                        attrs={'class': 'form-control'}
                    ),
            'brand': autocomplete.ModelSelect2(
                        url='basic:wordbook-autocomplete',
                        attrs={'class': 'form-control'},
                        forward=['type'],
                    ),
            'model': autocomplete.ModelSelect2(
                        url='basic:wordbook-autocomplete',
                        attrs={'class': 'form-control'},
                        forward=['name'],
                    ),
            'sn': TextInput(attrs={'class': 'form-control'}),
            'good': Select(attrs={'class': 'form-control'}),
        }

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        exclude = []

asset/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from dal import autocomplete

from asset.models import Device, Material
from asset.forms import DeviceForm, MaterialForm

class DeviceAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        # if not self.request.user.is_authenticated():
        #     return Country.objects.none()

        qs = Device.objects.all()

        if self.q:
            qs = qs.filter(sn__icontains=self.q)

        return qs

class DeviceList(ListView):
    model = Device


class DeviceCreate(CreateView):
    model = Device
    form_class = DeviceForm


class DeviceUpdate(UpdateView):
    model = Device
    form_class = DeviceForm


class DeviceDelete(DeleteView):
    model = Device
    success_url = reverse_lazy('asset:devices')


class MaterialList(ListView):
    model = Material


class MaterialCreate(CreateView):
    model = Material
    form_class = MaterialForm


class MaterialUpdate(UpdateView):
    model = Material
    form_class = MaterialForm


class MaterialDelete(DeleteView):
    model = Material
    success_url = reverse_lazy('asset:materials')

templates/asset/device_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'asset:devices' %}">设备列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data" class="col-md-10 col-md-offset-1">
    <table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th>设备ID</th>
                <th>类型</th>
                <th>名称/型号/序列号</th>
                <th>资产编码</th>
                <th>SAP编码</th>
                <!--<th>状态</th>-->
                <!--<th>审核</th>-->
                <th>创建时间</th>
                <th>备注</th>
                <th>操作</th>
            </tr>
        </thead>
        {% if object_list %}
        {% for d in object_list %}
        <tr>
            <th>{{ d.id }}</th>
            <th>{{ d.classification.name }}</th>
            <th>{{ d.get_device_display }}</th>
            <th>{{d.asset}}</th>
            <th>{{d.sap}}</th>
            <th>{{ d.modify_date }}</th>
            <th>{{ d.description }}</th>
            <th>
                <div class="hidden-sm hidden-xs btn-group">
                    <a class="btn btn-xs btn-info" href="{% url 'asset:edit_device' d.id %}">
                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                    </a>

                    <a class="btn btn-xs btn-danger" href="{% url 'asset:delete_device' d.id %}">
                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                    </a>
                </div>
            </th>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <th><strong>There are no devices present.</strong></th>
        </tr>
        {% endif %}
    </table>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/device.js"></script>
{% endblock %}

templates/asset/material_form.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'asset:materials' %}">材料列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data">
    <form id="materialForm" class="form-horizontal container" method="post" action="#">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        {% if form.non_field_errors %}
        <ul style="list-style-type:none">
            {% for error in form.non_field_errors %}
            <li align="center" class="text-warning">
                <h2>{{ error }}</h2>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="row">
            {% if form.classification.errors %}
            <div class="form-group col-md-6 has-warning">
                {% else %}
                <div class="form-group col-md-6">
                    {% endif %}
                    <label for="{{ form.classification.id_for_label }}"
                        class="col-sm-3 control-label"><strong>类型：</strong></label>
                    <div class="col-sm-8 input-group">
                        {{ form.classification }}
                        <span class="input-group-btn">
                            <button class="btn btn-info btn-xs" type="button" data-toggle="modal"
                                data-target="#addmaterialTypeamount">
                                <span class="glyphicon glyphicon-plus"></span>新增
                            </button>
                        </span>
                    </div>
                    {% if form.classification.errors %}
                    <ul style="list-style-type:none">
                        {% for error in form.classification.errors %}
                        <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                {% if form.name.errors %}
                <div class="form-group col-md-6 has-warning">
                    {% else %}
                    <div class="form-group col-md-6">
                        {% endif %}
                        <label for="{{ form.name.id_for_label }}"
                            class="col-sm-3 control-label"><strong>名称：</strong></label>
                        <div class="col-sm-8 input-group">
                            {{ form.name }}
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-xs" type="button" data-toggle="modal"
                                    data-target="#addmaterialnameamount">
                                    <span class="glyphicon glyphicon-plus"></span>新增
                                </button>
                            </span>
                        </div>
                        {% if form.name.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.name.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>

                <div class="row">
                    {% if form.amount.errors %}
                    <div class="form-group col-md-6 has-warning">
                        {% else %}
                        <div class="form-group col-md-6">
                            {% endif %}
                            <label for="{{ form.amount.id_for_label }}"
                                class="col-sm-3 control-label"><strong>数量：</strong></label>
                            <div class="col-sm-8 input-group">
                                {{ form.amount }}
                                <span class="input-group-btn">
                                    <button class="btn btn-info btn-xs" type="button" data-toggle="modal"
                                        data-target="#addmaterialamountamount">
                                        <span class="glyphicon glyphicon-plus"></span>新增
                                    </button>
                                </span>
                            </div>
                            {% if form.amount.errors %}
                            <ul style="list-style-type:none">
                                {% for error in form.amount.errors %}
                                <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>



                        <div class="row">


                            {% if form.warehouse.errors %}
                            <div class="form-group col-md-6 has-warning">
                                {% else %}
                                <div class="form-group col-md-6">
                                    {% endif %}
                                    <label for="{{ form.warehouse.id_for_label }}"
                                        class="col-sm-3 control-label">所在库房：</label>
                                    <div class="col-sm-8">
                                        {{ form.warehouse }}
                                    </div>
                                    {% if form.warehouse.errors %}
                                    <ul style="list-style-type:none">
                                        {% for error in form.warehouse.errors %}
                                        <li align="center" class="text-warning"><strong>{{ error }}</strong>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="row">
                                {% if form.description.errors %}
                                <div class="form-group col-md-6 has-warning">
                                    {% else %}
                                    <div class="form-group col-md-6">
                                        {% endif %}
                                        <label for="{{ form.description.id_for_label }}"
                                            class="col-sm-3 control-label">备注：</label>
                                        <div class="col-sm-8">
                                            {{ form.description }}
                                        </div>
                                        {% if form.description.errors %}
                                        <ul style="list-style-type:none">
                                            {% for error in form.description.errors %}
                                            <li align="center" class="text-warning">
                                                <strong>{{ error }}</strong></li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-11">
                                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                                        <button type="button" class="btn btn-default">取消</button>
                                    </div>
                                </div>
                                {% if alert == 'T' %}
                                <div id="alert" class="alert alert-dismissable alert-success">设备添加成功！</div>
                                {% elif alert == 'F' %}
                                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试
                                </div>
                                {% else %}
                                <div id="alert"></div>
                                {% endif %}
    </form>
</div>
{% endblock maincontent%}

templates/asset/material_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'asset:materials' %}">设备列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data" class="col-md-10 col-md-offset-1">
    <table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>所属分类</th>
                <th>数量</th>
                <th>库房</th>
                <th>备注</th>
                <th>操作</th>
            </tr>
        </thead>
        {% if object_list %}
        {% for m in object_list %}
        <tr>
            <th>{{ m.id }}</th>
            <th>{{ m.name.name }}</th>
            <th>{{ m.classification.name }}</th>
            <th>{{ m.amount }}</th>
            <th>{{ m.warehouse.name }}</th>
            <th>{{ m.description }}</th>
            <th>
                <div class="hidden-sm hidden-xs btn-group">
                    <a class="btn btn-xs btn-info" href="{% url 'asset:edit_material' m.id %}">
                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                    </a>

                    <a class="btn btn-xs btn-danger" href="{% url 'asset:delete_material' m.id %}">
                        <i class="ace-icon fa fa-trash-o bimgger-120"></i>
                    </a>
                </div>
            </th>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <th><strong>There are no materials present.</strong></th>
        </tr>
        {% endif %}
    </table>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/material.js"></script>
{% endblock %}