basic/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete
from basic.views import WordbookList, WordbookCreate, WordbookUpdate, WordbookDelete, WordbookAutocomplete
from basic.views import WarehouseList, WarehouseCreate, WarehouseUpdate, WarehouseDelete

app_name = 'basic'

urlpatterns = [
    path('categories', CategoryList.as_view(), name='categories'),
    path('category/add', CategoryCreate.as_view(), name='add_category'),
    path('category/<int:pk>/', CategoryUpdate.as_view(), name='edit_category'),
    path('category/<int:pk>/delete',
         CategoryDelete.as_view(),
         name='delete_category'),
    path('wordbooks', WordbookList.as_view(), name='wordbooks'),
    path('wordbook/add', WordbookCreate.as_view(), name='add_wordbook'),
    path('wordbook/<int:pk>/', WordbookUpdate.as_view(), name='edit_wordbook'),
    path('wordbook/<int:pk>/delete',
         WordbookDelete.as_view(),
         name='delete_wordbook'),
     path('wordbook-autocomplete/', WordbookAutocomplete.as_view(), name='wordbook-autocomplete'),
    path('warehouses', WarehouseList.as_view(), name='warehouses'),
    path('warehouse/add', WarehouseCreate.as_view(), name='add_warehouse'),
    path('warehouse/<int:pk>/', WarehouseUpdate.as_view(), name='edit_warehouse'),
    path('warehouse/<int:pk>/delete',
         WarehouseDelete.as_view(),
         name='delete_warehouse'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', views.index, name = 'index'),
    path('stock/', include('stock.urls')),
    path('basic/', include('basic.urls')),
    path('asset/', include('asset.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete

from user.views import UserProfileList, UserProfileCreate, UserProfileUpdate, UserProfileDelete, UserProfileAutocomplete

app_name = 'user'

urlpatterns = [
    path('profiles', UserProfileList.as_view(), name='profiles'),
    path('profile/add', UserProfileCreate.as_view(), name='add_profile'),
    path('profile/<int:pk>/', UserProfileUpdate.as_view(),
         name='edit_profile'),
    path('profile/<int:pk>/delete',
         UserProfileDelete.as_view(),
         name='delete_profile'),
path('employee-autocomplete/', UserProfileAutocomplete.as_view(), name='employee-autocomplete'),
]

basic/models.py
from django.db import models
from django.urls import reverse

from basic.utils import time2str, str2time


class CommonInfo(models.Model):
    check_choice = (
        (True, u'已审核'),
        (False, u'未审核'),
    )
    #history = AuditlogHistoryField()

    attach = models.FileField(upload_to='attachment/%Y/%m/%d',
                              verbose_name='附件',
                              blank=True,
                              null=True)
    check = models.BooleanField(default=False,
                                choices=check_choice,
                                verbose_name=u"是否审核")
    create_date = models.DateTimeField(blank=True,
                                       null=True,
                                       auto_now_add=True,
                                       verbose_name=u"创建时间")
    modify_date = models.DateTimeField(blank=True,
                                       null=True,
                                       auto_now=True,
                                       verbose_name=u"修改时间")
    description = models.CharField(max_length=100,
                                   blank=True,
                                   null=True,
                                   verbose_name=u"备注")

    def dict(self):
        return {
            'create_date': time2str(self.create_date),
            'check': self.check,
            'description': self.description
        }

    @property
    def created(self):
        return time2str(self.create_date)

    @property
    def modified(self):
        return time2str(self.modify_date)

    def get_create_date_display(self):
        return time2str(self.create_date)

    class Meta:
        app_label = 'stock'
        abstract = True
        ordering = ['-modify_date']


class Category(CommonInfo):
    name = models.CharField(max_length=30,
                            unique=True,
                            verbose_name=u"名称",
                            db_index=True)

    def __str__(self):
        return self.name

    def get_type_display(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic:edit_category', args=[str(self.id)])

    class Meta:
        verbose_name = u'类型表'
        verbose_name_plural = u'类型表'


# 用来存出重复的内容，例如各种分类、品牌型号、部门班组
class Wordbook(CommonInfo):
    name = models.CharField(max_length=30,
                            unique=True,
                            verbose_name=u"名称",
                            db_index=True)

    def __str__(self):
        return self.name

    def get_type_display(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic:edit_wordbook', args=[str(self.id)])

    class Meta:
        verbose_name = u'字典表'
        verbose_name_plural = u'字典表'


# 建立多对多映射关系，例如某个品牌可以同时存在于设备、材料等分类中
class WordbookShip(models.Model):
    item = models.ForeignKey(Wordbook, null=True, blank=True, verbose_name="词典条目", on_delete=models.CASCADE, related_name="items")
    parent = models.ForeignKey(Wordbook, null=True, blank=True, verbose_name="父节点", on_delete=models.SET_NULL, related_name="parents")

    class Meta:
        verbose_name = '字典关系映射表'
        verbose_name_plural = '字典关系映射表'


class Warehouse(CommonInfo):
    name = models.CharField(max_length=30,
                            unique=True,
                            verbose_name=u"名称",
                            db_index=True)
    location = models.CharField(max_length=50, unique=True, verbose_name=u"位置")

    def __str__(self):
        return self.name + ' ' + self.location

    def get_warehouse_dispaly(self):
        return self.name

    def dict(self):
        d = {'id': self.id, 'name': self.name, 'location': self.location}
        d.update(super(Warehouse, self).dict())
        return d

    class Meta:
        verbose_name = u'库房表'
        verbose_name_plural = u'库房表'

basic/forms.py
from django.forms import ModelForm

from basic.models import Category, Wordbook, Warehouse


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        exclude = ['check', 'create_date', 'modify_date']


class WordbookForm(ModelForm):
    class Meta:
        model = Wordbook
        exclude = ['check', 'create_date', 'modify_date']


class WarehouseForm(ModelForm):
    class Meta:
        model = Warehouse
        exclude = ['check', 'create_date', 'modify_date']

basic/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from dal import autocomplete

from config.settings import ITEMS_PER_PAGE

from basic.models import Wordbook, Category, Warehouse
from basic.forms import WordbookForm, CategoryForm, WarehouseForm


class CategoryList(ListView):
    model = Category


class CategoryCreate(CreateView):
    model = Category
    fields = ['name', 'description']


class CategoryUpdate(UpdateView):
    model = Category
    fields = ['name', 'description']


class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('categories')


class WordbookList(ListView):
    model = Wordbook
    paginate_by = ITEMS_PER_PAGE

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WordbookList, self).get_context_data(**kwargs)
        context['theurl'] = reverse_lazy("basic:wordbooks")
        return context    


class WordbookCreate(CreateView):
    model = Wordbook
    form_class = WordbookForm


class WordbookUpdate(UpdateView):
    model = Wordbook
    form_class = WordbookForm


class WordbookDelete(DeleteView):
    model = Wordbook
    success_url = reverse_lazy('wordbooks')

class WordbookAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        # if not self.request.user.is_authenticated():
        #     return Country.objects.none()

        qs = Wordbook.objects.all()

        if self.q:
            qs = qs.filter(sn__icontains=self.q)

        return qs

class WarehouseList(ListView):
    model = Warehouse
    paginate_by = ITEMS_PER_PAGE


class WarehouseCreate(CreateView):
    model = Warehouse
    form_class = WarehouseForm


class WarehouseUpdate(UpdateView):
    model = Warehouse
    form_class = WarehouseForm


class WarehouseDelete(DeleteView):
    model = Warehouse
    success_url = reverse_lazy('Warehouses')

templates/basic/category_form.html
{% extends 'base.html' %}

{% block title %}
分类详情
{% endblock %}

{% block breadcrumb %}
<li id="categories"><a href="{%url 'basic:categories' %}">分类信息</a></li>
{% endblock %}

{% block maincontent %}
<form id="categoryForm" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if form.non_field_errors %}
            <ul style="list-style-type:none">
                {% for error in form.non_field_errors %}
                <li align="center" class="text-warning">
                    <h2>{{ error }}</h2>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="row">
                {% if form.name.errors %}
                <div class="form-group col-md-6 has-warning">
                    {% else %}
                    <div class="form-group col-md-6">
                        {% endif %}
                        <label for="{{ form.name.id_for_label }}"
                            class="col-sm-4 control-label"><strong>名称：</strong></label>
                        <div class="col-sm-8">
                            {{ form.name }}
                        </div>
                        {% if form.name.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.name.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <div class="row">
                        {% if form.description.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                class="form-group col-md-6">{% endif %}
                                <label for="{{ form.description.id_for_label }}"
                                    class="col-sm-4 control-label">备注：</label>
                                <div class="col-sm-8">
                                    {{ form.description }}
                                </div>
                                {% if form.description.errors %}
                                <ul style="list-style-type:none">
                                    {% for error in form.description.errors %}
                                    <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-11">
                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                        <button type="button" class="btn btn-default">取消</button>
                    </div>
                </div>
                {% if alert == 'T' %}
                <div id="alert" class="alert alert-dismissable alert-success">库房信息添加成功！</div>
                {% elif alert == 'F' %}
                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
                {% else %}
                <div id="alert"></div>
                {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/basic/category_list.html
{% extends 'base.html' %}

{% block title %}
分类列表
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'basic:categories' %}">分类信息</a></li>
{% endblock %}

{% block maincontent %}
<div id="data" class="col-md-10 col-md-offset-1">
	<table id='dataTable' class="table  table-bordered table-hover" cellspacing='0' width='100%'>
		<thead>
			<tr>
				<th>ID</th>
				<th>名称</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
		</thead>
		{% if object_list %}
		{% for c in object_list %}
		<tr>
			<th>{{ c.id }}</th>
			<th>{{ c.name }}</th>
			<th>{{ c.description }}</th>
			<th>
				<div class="hidden-sm hidden-xs btn-group">
					<a class="btn btn-xs btn-info" href="{% url 'basic:edit_category' c.id %}">
						<i class="ace-icon fa fa-pencil bigger-120"></i>
					</a>

					<a class="btn btn-xs btn-danger" href="{% url 'basic:delete_category' c.id %}">
						<i class="ace-icon fa fa-trash-o bigger-120"></i>
					</a>
				</div>
			</th>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<th><strong>There are no categories present.</strong></th>
		</tr>
		{% endif %}
		<tfoot>
			<tr>
				<th>ID</th>
				<th>名称</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
		</tfoot>
	</table>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/basic/warehouse_form.html
{% extends 'base.html' %}

{% block title %}
库房详情
{% endblock %}

{% block breadcrumb %}
<li id="warehouse"><a href="{%url 'basic:warehouses' %}">库房信息</a></li>
{% endblock %}

{% block maincontent %}
<form id="warehouseForm" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if form.non_field_errors %}
            <ul style="list-style-type:none">
                {% for error in form.non_field_errors %}
                <li align="center" class="text-warning">
                    <h2>{{ error }}</h2>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="row">
                {% if form.name.errors %}
                <div class="form-group col-md-6 has-warning">
                    {% else %}
                    <div class="form-group col-md-6">
                        {% endif %}
                        <label for="{{ form.name.id_for_label }}"
                            class="col-sm-4 control-label"><strong>库房名称：</strong></label>
                        <div class="col-sm-8">
                            {{ form.name }}
                        </div>
                        {% if form.name.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.name.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    {% if form.location.errors %}
                    <div class="form-group col-md-6 has-warning">
                        {% else %}
                        <div class="form-group col-md-6">
                            {% endif %}
                            <label for="{{ form.location.id_for_label }}"
                                class="col-sm-4 control-label"><strong>库房位置：</strong></label>
                            <div class="col-sm-8">
                                {{ form.location }}
                            </div>
                            {% if form.location.errors %}
                            <ul style="list-style-type:none">
                                {% for error in form.location.errors %}
                                <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row">
                        {% if form.description.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                class="form-group col-md-6">{% endif %}
                                <label for="{{ form.description.id_for_label }}"
                                    class="col-sm-4 control-label">备注：</label>
                                <div class="col-sm-8">
                                    {{ form.description }}
                                </div>
                                {% if form.description.errors %}
                                <ul style="list-style-type:none">
                                    {% for error in form.description.errors %}
                                    <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-11">
                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                        <button type="button" class="btn btn-default">取消</button>
                    </div>
                </div>
                {% if alert == 'T' %}
                <div id="alert" class="alert alert-dismissable alert-success">库房信息添加成功！</div>
                {% elif alert == 'F' %}
                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
                {% else %}
                <div id="alert"></div>
                {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/basic/warehouse_list.html
{% extends 'base.html' %}

{% block title %}
库房列表
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'basic:warehouses' %}">库房信息</a></li>
{% endblock %}

{% block maincontent %}
<div id="data">
	<table id='dataTable' class='table  table-bordered table-hover' cellspacing='0' width='100%'>
		<thead>
			<tr>
				<th>ID</th>
				<th>仓库名称</th>
				<th>位置</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
		</thead>
		{% if warehouses %}
		{% for w in warehouses %}
		<tr>
			<th>{{ w.id }}</th>
			<th>{{ w.name }}</th>
			<th>{{ w.location }}</th>
			<th>{{ w.description }}</th>
			<th>
				<div class="hidden-sm hidden-xs btn-group">
					<a class="btn btn-xs btn-info" href="{% url 'basic:edit_category' c.id %}">
						<i class="ace-icon fa fa-pencil bigger-120"></i>
					</a>

					<a class="btn btn-xs btn-danger" href="{% url 'basic:delete_category' c.id %}">
						<i class="ace-icon fa fa-trash-o bigger-120"></i>
					</a>
				</div>
			</th>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<th colspan='5' align="center"><strong>There are no warehouses present.</strong></th>
		</tr>
	</table>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/basic/wordbook_form.html
{% extends 'base.html' %}

{% block title %}
库房详情
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'basic:wordbooks' %}">字典列表</a></li>
{% endblock %}

{% block maincontent %}
<form id="warehouseForm" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if form.non_field_errors %}
            <ul style="list-style-type:none">
                {% for error in form.non_field_errors %}
                <li align="center" class="text-warning">
                    <h2>{{ error }}</h2>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="row">
                {% if form.name.errors %}
                <div class="form-group col-md-6 has-warning">
                    {% else %}
                    <div class="form-group col-md-6">
                        {% endif %}
                        <label for="{{ form.name.id_for_label }}"
                            class="col-sm-4 control-label"><strong>名称：</strong></label>
                        <div class="col-sm-8">
                            {{ form.name }}
                        </div>
                        {% if form.name.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.name.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    {% if form.location.errors %}
                    <div class="form-group col-md-6 has-warning">
                        {% else %}
                        <div class="form-group col-md-6">
                            {% endif %}
                            <label for="{{ form.parent.id_for_label }}"
                                class="col-sm-4 control-label"><strong>父节点：</strong></label>
                            <div class="col-sm-8">
                                {{ form.parent }}
                            </div>
                            {% if form.parent.errors %}
                            <ul style="list-style-type:none">
                                {% for error in form.parent.errors %}
                                <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>

                    {% if form.categories.errors %}
                    <div class="form-group col-md-6 has-warning">
                        {% else %}
                        <div class="form-group col-md-6">
                            {% endif %}
                            <label for="{{ form.categories.id_for_label }}"
                                class="col-sm-4 control-label"><strong>所属分类：</strong></label>
                            <div class="col-sm-8">
                                {{ form.categories }}
                            </div>
                            {% if form.categories.errors %}
                            <ul style="list-style-type:none">
                                {% for error in form.categories.errors %}
                                <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row">
                        {% if form.description.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                class="form-group col-md-6">{% endif %}
                                <label for="{{ form.description.id_for_label }}"
                                    class="col-sm-4 control-label">备注：</label>
                                <div class="col-sm-8">
                                    {{ form.description }}
                                </div>
                                {% if form.description.errors %}
                                <ul style="list-style-type:none">
                                    {% for error in form.description.errors %}
                                    <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-11">
                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                        <button type="button" class="btn btn-default">取消</button>
                    </div>
                </div>
                {% if alert == 'T' %}
                <div id="alert" class="alert alert-dismissable alert-success">库房信息添加成功！</div>
                {% elif alert == 'F' %}
                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
                {% else %}
                <div id="alert"></div>
                {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/basic/wordbook_list.html
{% extends 'base.html' %}

{% block title %}
字典列表
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'basic:wordbooks' %}">字典列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data" class="col-md-10 col-md-offset-1">
	{% if object_list %}
	<table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
		<thead>
			<tr>
				<th>ID</th>
				<th>名称</th>
				<th>父节点</th>
				<th>所属分类</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
		</thead>
		{% for w in object_list %}
		<tr>
			<th>{{ w.id }}</th>
			<th>{{ w.name }}</th>
			<th>{{ w.parent.name }}</th>
			<th>
				{% for c in w.categories.all %}
				{{c.name}},
				{% endfor %}
			</th>
			<th>{{ w.description }}</th>
			<th>
				<div class="hidden-sm hidden-xs btn-group">
					<a class="btn btn-xs btn-info" href="{% url 'basic:edit_wordbook' w.id %}">
						<i class="ace-icon fa fa-pencil bigger-120"></i>
					</a>

					<a class="btn btn-xs btn-danger" href="{% url 'basic:delete_wordbook' w.id %}">
						<i class="ace-icon fa fa-trash-o bigger-120"></i>
					</a>
				</div>
			</th>
		</tr>
		{% endfor %}
	</table>
	{% include "paginate.html" %}
	{% else %}
	<tr>
		<th><strong>There are no warehouses present.</strong></th>
	</tr>
	{% endif %}


</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}