config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', views.index, name = 'index'),
    path('stock/', include('stock.urls')),
    path('basic/', include('basic.urls')),
    path('asset/', include('asset.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path
from stock.views import DeviceOperateList, DeviceOperateCreate, DeviceOperateUpdate, DeviceOperateDelete
from stock.views import ApplicationList, ApplicationCreate, ApplicationUpdate, ApplicationDelete

app_name = 'stock'

urlpatterns = [
    # display all device in and out records
    path('deviceoperates', DeviceOperateList.as_view(), name='deviceoperates'),
    path('deviceoperate/<int:pk>/delete', DeviceOperateDelete.as_view(), name='delete_deviceoperate'),
    # device in operate
    path('deviceins', DeviceOperateList.as_view(), {'operate': 1}, name='deviceins'),
    path('devicein/add', DeviceOperateCreate.as_view(), {'operate': 1}, name='add_devicein'),
    path('devicein/<int:pk>/', DeviceOperateUpdate.as_view(), {'operate': 1}, name='edit_devicein'),
    # device out operate
    path('deviceouts', DeviceOperateList.as_view(), {'operate': 2}, name='deviceouts'),
    path('deviceout/add', DeviceOperateCreate.as_view(), {'operate': 2}, name='add_deviceout'),
    path('deviceout/<int:pk>/', DeviceOperateUpdate.as_view(), {'operate': 2}, name='edit_deviceout'),

    path('applications', ApplicationList.as_view(), name='applications'),
    path('application/add', ApplicationCreate.as_view(), name='add_application'),
    path('application/<int:pk>/', ApplicationUpdate.as_view(), name='edit_application'),
    path('application/<int:pk>/delete', ApplicationDelete.as_view(), name='delete_application'),
]

user/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete

from user.views import UserProfileList, UserProfileCreate, UserProfileUpdate, UserProfileDelete, UserProfileAutocomplete

app_name = 'user'

urlpatterns = [
    path('profiles', UserProfileList.as_view(), name='profiles'),
    path('profile/add', UserProfileCreate.as_view(), name='add_profile'),
    path('profile/<int:pk>/', UserProfileUpdate.as_view(),
         name='edit_profile'),
    path('profile/<int:pk>/delete',
         UserProfileDelete.as_view(),
         name='delete_profile'),
path('employee-autocomplete/', UserProfileAutocomplete.as_view(), name='employee-autocomplete'),
]

stock/forms.py
import datetime

from django import forms
from django.forms import TextInput, Textarea, Select

from dal import autocomplete

from asset.models import Device
from stock.models import DeviceOperate, MaterialIn, Application, ApplicationDetail
from django.forms.models import inlineformset_factory

class DeviceOperateForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}), required=False)

    class Meta:
        model = DeviceOperate
        fields = ['id', 'device', 'warehouse', 'employee', 'description']
        widgets = {
            'device': autocomplete.ModelSelect2(
                            url='asset:device-autocomplete',
                            attrs={'class': 'form-control'}
                        ),
            'warehouse': Select(attrs={'class': 'form-control'}),
            'employee': autocomplete.ModelSelect2(
                            url='user:employee-autocomplete',
                            attrs={'class': 'form-control'}
                        ),
        }    

class MaterialInForm(forms.ModelForm):
    class Meta:
        model = MaterialIn
        exclude = ['check', 'create_date', 'modify_date']


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['id', 'name', 'applicant', 'status', 'approver', 'approve_content', 'approve_date',
                    'confirmed', 'confirm_content', 'confirm_date', 'description']

DetailFormSet = inlineformset_factory(Application, ApplicationDetail, fields=('name', 'number', 'location', 'is_device', 'description'),
                                          extra=10, can_delete=False, max_num=15)
class ApplicationDetailForm(forms.ModelForm):
    class Meta:
        model = ApplicationDetail
        fields = ['name', 'number', 'location', 'is_device', 'description']                    

stock/views.py
from django.shortcuts import render, redirect
from django.forms import formset_factory
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from config.settings import ITEMS_PER_PAGE

from asset.forms import DeviceForm
from stock.models import DeviceOperate, MaterialIn, Application, ApplicationDetail
from stock.forms import ApplicationDetailForm, ApplicationForm, DetailFormSet, DeviceOperateForm, MaterialInForm
from django.http import HttpResponseRedirect


class DeviceOperateList(ListView):
    model = DeviceOperate
    paginate_by = ITEMS_PER_PAGE

    def get_queryset(self):
        if self.kwargs["operate"] == 1 or self.kwargs["operate"] == 2:
            return DeviceOperate.objects.filter(operate=self.kwargs["operate"])
        else:            
            return DeviceOperate.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DeviceOperateList, self).get_context_data(**kwargs)
        context['theurl'] = reverse_lazy("stock:deviceins")
        context['operate']=self.kwargs["operate"]
        return context    

class DeviceOperateCreate(CreateView):
    model = DeviceOperate
    form_class = DeviceOperateForm

    def get_context_data(self, **kwargs):
        context = super(DeviceOperateCreate, self).get_context_data(**kwargs)
        context['operate'] = self.kwargs["operate"]
        context['new']=1
        return context

    def form_valid(self, form):
        deviceop = form.save(commit=False)
        deviceop.location = ""
        if self.kwargs["operate"] == 1 or self.kwargs["operate"] == 2:
            deviceop.operate = self.kwargs["operate"]
        else:
            deviceop.operate = 0
        deviceop.save()
        
        return super(DeviceOperateCreate, self).form_valid(form)


class DeviceOperateUpdate(UpdateView):
    model = DeviceOperate
    form_class = DeviceOperateForm



class DeviceOperateDelete(DeleteView):
    model = DeviceOperate
    success_url = reverse_lazy('stock:DeviceOperates')


class MaterialInList(ListView):
    model = MaterialIn


class MaterialInCreate(CreateView):
    model = MaterialIn
    form_class = MaterialInForm


class MaterialInUpdate(UpdateView):
    model = MaterialIn
    form_class = MaterialInForm


class MaterialInDelete(DeleteView):
    model = MaterialIn
    success_url = reverse_lazy('stock:materialins')


class ApplicationList(ListView):
    model = Application

set_data = {'form-TOTAL_FORMS': '10', 'form-INITIAL_FORMS': '10', 'form-MAX_NUM_FORMS': '10' }

class ApplicationCreate(CreateView):
    model = Application
    form_class = ApplicationForm

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detailSets = DetailFormSet()
        return self.render_to_response(self.get_context_data(form=form, detailSets=detailSets))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detailSets = DetailFormSet(self.request.POST)
        if detailSets.is_valid():
            return self.form_valid(form, detailSets)
        else:
            return self.form_invalid(form, detailSets)

    def form_valid(self, form, detailSets):
        """
        Called if all forms are valid. Creates a Recipe instance along with
        associated Ingredients and Instructions and then redirects to a
        success page.
        """
        self.object = form.save()
        detailSets.instance = self.object
        detailSets.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, detailSets):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form, detailSets=detailSets))


class ApplicationUpdate(UpdateView):
    model = Application
    form_class = ApplicationForm

    def get_context_data(self, **kwargs):
        context = super(ApplicationUpdate, self).get_context_data(**kwargs)
        #处理数据库记录对应的表单
        details={}
        if self.request.method == 'POST':
            for i in range(10):
                details[i] = ApplicationDetailForm(self.request.POST, prefix='detailForm'+str(i))
        else:
            for i in range(10):
                details[i] = ApplicationDetailForm(prefix='detailForm'+str(i))
        #注意要把自己处理的表单放到context上下文中，供模板文件使用
        for i in range(10):
            context['detailForm'+str(i)] = details[i]
        return context

    def form_valid(self, form):
	    #保存Application
        application = form.save()
		#获取上面get_context_data方法中在POST里得到的表单
        context = self.get_context_data()
        for i in range(10):	
            detail = context['detailForm' + str(i)].save(commit=False)
            detail.application = application
            detail.save()
                
        return super(ApplicationUpdate, self).form_valid(form)


class ApplicationDelete(DeleteView):
    model = Application
    success_url = reverse_lazy('stock:Applications')

templates/stock/application_form.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}
库房详情
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'stock:applications' %}">设备入库列表</a></li>
{% endblock %}

{% block maincontent %}
<form id="applicationForm" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}
    <!-- hidden fields -->
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {{ detailSets.management_form }}

    <!-- application detail forms -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">设备材料申请</h3>
        </div>
        <table class="table" align="center">
            <tr>
                <th>
                    <h5><strong>设备描述</strong></h5>
                </th>
                <th>
                    <h5><strong>设备数量(仅为数字)</strong></h5>
                </th>
                <th>
                    <h5><strong>安装位置</strong></h5>
                </th>
            </tr>
            {% for df in detailSets %}
            {% for hidden in df.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            <tr>
                {% if df.name.errors %}
                <th class="has-warning">
                    {% else %}
                <th>
                    {% endif %}
                    {{ df.name }}
                    {% if df.name.errors %}
                    <ul style="list-style-type:none">
                        {% for error in df.name.errors %}
                        <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </th>
                {% if df.number.errors %}
                <th class="has-warning">
                    {% else %}
                <th>
                    {% endif %}
                    {{ df.number }}
                    {% if df.number.errors %}
                    <ul style="list-style-type:none">
                        {% for error in df.number.errors %}
                        <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </th>
                {% if df.location.errors %}
                <th class="has-warning">
                    {% else %}
                <th>
                    {% endif %}
                    {{ df.location }}
                    {% if df.location.errors %}
                    <ul style="list-style-type:none">
                        {% for error in df.location.errors %}
                        <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            {% if form.non_field_errors %}
            <ul style="list-style-type:none">
                {% for error in form.non_field_errors %}
                <li align="center" class="text-warning">
                    <h2>{{ error }}</h2>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="row">
                {% if form.applicant.errors %}
                <div class="form-group col-md-6 has-warning">
                    {% else %}
                    <div class="form-group col-md-6">
                        {% endif %}
                        <label for="{{ form.applicant.id_for_label }}"
                            class="col-sm-4 control-label"><strong>申请人：</strong></label>
                        <div class="col-sm-8">
                            {{ form.applicant }}
                        </div>
                        {% if form.applicant.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.applicant.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-11">
                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                        <button type="button" class="btn btn-default">取消</button>
                    </div>
                </div>
                {% if alert == 'T' %}
                <div id="alert" class="alert alert-dismissable alert-success">库房信息添加成功！</div>
                {% elif alert == 'F' %}
                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
                {% else %}
                <div id="alert"></div>
                {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/stock/application_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li id="orbit" class="active"><a href="{%url 'stock:deviceins' %}">设备入库列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data">
    {% if object_list %}
    <table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>申请人</th>
                <th>状态</th>
                <th>申请时间</th>
                <th>备注</th>
                <th>操作</th>
            </tr>
        </thead>
        {% for d in object_list %}
        <tr>
            <th>{{ d.id }}</th>
            <th>{{ d.name }}</th>
            <th>{{ d.applicant }}</th>
            <th>{{ d.status }}</th>
            <th>{{ d.created }}</th>
            <th>{{ d.description }}</th>
            <th>
                <div class="hidden-sm hidden-xs btn-group">
                    <a class="btn btn-xs btn-info" href="{% url 'stock:edit_application' d.id %}">
                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                    </a>

                    <a class="btn btn-xs btn-danger" href="{% url 'stock:delete_application' d.id %}">
                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                    </a>
                </div>
            </th>
        </tr>
        {% endfor %}
    </table>
    {% include "paginate.html" %}
    {% else %}
    <strong>There are no applications present.</strong>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/application.js"></script>
{% endblock %}

templates/stock/deviceoperate_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %}
新增设备入库
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'stock:deviceins' %}">设备入库列表</a></li>
<li id="orbit" class="active">
    {% if new %}
    新增设备入库
    {% else %}
    设备入库更新
    {% endif %}
</li>
{% endblock %}

{% block maincontent %}
<form id="warehouseForm" role="form" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}

    <div class="widget-box">
        <div class="widget-header">
            <h4 class="widget-title">入库信息</h4>
            <div class="widget-toolbar">
                <a href="#" data-action="collapse">
                    <i class="ace-icon fa fa-chevron-up"></i>
                </a>
                <a href="#" data-action="close">
                    <i class="ace-icon fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    <div class="col-sm-2">{{ field.label_tag }}</div>
                    <div class="col-sm-10">{{ field }}</div>
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-11">
            <button id="oper" type="submit" class="btn btn-primary">确认</button>
            <button type="button" class="btn btn-default">取消</button>
        </div>
    </div>
    {% if alert == 'T' %}
    <div id="alert" class="alert alert-dismissable alert-success">库房信息添加成功！</div>
    {% elif alert == 'F' %}
    <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
    {% else %}
    <div id="alert"></div>
    {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/stock/deviceoperate_list.html
{% extends 'base.html' %}

{% block title %}
字典列表
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'stock:deviceins' %}">设备入库列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data" class="col-md-10 col-md-offset-1">
	{% if object_list %}
	<table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
		<thead>
			<tr>
				<th>ID</th>
				<th>名称/型号/序列号</th>
				<th>入库人</th>
				<th>所在库房</th>
				<th>备注</th>
				<th>操作</th>
			</tr>
		</thead>
		{% for d in object_list %}
		<tr>
			<th>{{ d.id }}</th>
			<th>{{ d.device.get_device_display }}</th>
			<th>{{ d.employee }}</th>
			<th>{{ d.warehouse }}</th>
			<th>{{ d.description }}</th>
			<th>
				<div class="hidden-sm hidden-xs btn-group">
					<a class="btn btn-xs btn-info" href="{% url 'stock:edit_devicein' d.id %}">
						<i class="ace-icon fa fa-pencil bigger-120"></i>
					</a>

					<a class="btn btn-xs btn-danger" href="{% url 'stock:delete_deviceoperate' d.id %}">
						<i class="ace-icon fa fa-trash-o bigger-120"></i>
					</a>
				</div>
			</th>
		</tr>
		{% endfor %}
	</table>
	{% include "paginate.html" %}
	{% else %}
	<strong>There are no device stockin present.</strong>
	{% endif %}

</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}