basic/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete
from basic.views import WordbookList, WordbookCreate, WordbookUpdate, WordbookDelete, WordbookAutocomplete
from basic.views import WarehouseList, WarehouseCreate, WarehouseUpdate, WarehouseDelete

app_name = 'basic'

urlpatterns = [
    path('categories', CategoryList.as_view(), name='categories'),
    path('category/add', CategoryCreate.as_view(), name='add_category'),
    path('category/<int:pk>/', CategoryUpdate.as_view(), name='edit_category'),
    path('category/<int:pk>/delete',
         CategoryDelete.as_view(),
         name='delete_category'),
    path('wordbooks', WordbookList.as_view(), name='wordbooks'),
    path('wordbook/add', WordbookCreate.as_view(), name='add_wordbook'),
    path('wordbook/<int:pk>/', WordbookUpdate.as_view(), name='edit_wordbook'),
    path('wordbook/<int:pk>/delete',
         WordbookDelete.as_view(),
         name='delete_wordbook'),
     path('wordbook-autocomplete/', WordbookAutocomplete.as_view(), name='wordbook-autocomplete'),
    path('warehouses', WarehouseList.as_view(), name='warehouses'),
    path('warehouse/add', WarehouseCreate.as_view(), name='add_warehouse'),
    path('warehouse/<int:pk>/', WarehouseUpdate.as_view(), name='edit_warehouse'),
    path('warehouse/<int:pk>/delete',
         WarehouseDelete.as_view(),
         name='delete_warehouse'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('', views.index, name = 'index'),
    path('stock/', include('stock.urls')),
    path('basic/', include('basic.urls')),
    path('asset/', include('asset.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from basic.views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete

from user.views import UserProfileList, UserProfileCreate, UserProfileUpdate, UserProfileDelete, UserProfileAutocomplete

app_name = 'user'

urlpatterns = [
    path('profiles', UserProfileList.as_view(), name='profiles'),
    path('profile/add', UserProfileCreate.as_view(), name='add_profile'),
    path('profile/<int:pk>/', UserProfileUpdate.as_view(),
         name='edit_profile'),
    path('profile/<int:pk>/delete',
         UserProfileDelete.as_view(),
         name='delete_profile'),
path('employee-autocomplete/', UserProfileAutocomplete.as_view(), name='employee-autocomplete'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

from basic.models import Wordbook, CommonInfo


class Role(CommonInfo):
    name = models.CharField(max_length=30,
                            unique=True,
                            verbose_name=u"名称",
                            db_index=True)

    def __unicode__(self):
        return self.name

    def dict(self):
        d = {'id': self.id, 'name': self.name}
        d.update(super(Role, self).dict())
        return d

    class Meta:
        verbose_name = u'角色表'
        verbose_name_plural = u'角色表'


class UserProfile(CommonInfo):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name='profile')
    name = models.CharField('姓名', max_length=50, blank=True, null=True)
    department = models.ForeignKey(Wordbook,
                                   on_delete=models.SET_NULL,
                                   related_name='dep_users',
                                   blank=True,
                                   null=True)
    team = models.ForeignKey(Wordbook,
                             on_delete=models.SET_NULL,
                             related_name='team_users',
                             blank=True,
                             null=True)
    role = models.ForeignKey(Role,
                             on_delete=models.SET_NULL,
                             blank=True,
                             null=True,
                             verbose_name=u"角色")
    phone = models.CharField('固定电话', max_length=50, blank=True, null=True)
    mobile = models.CharField('电话', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = '用户信息'

    def __str__(self):
        return self.user.__str__()

user/forms.py
from django.forms import ModelForm

from user.models import UserProfile


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['mod_date']

user/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from dal import autocomplete

from user.models import UserProfile
from user.forms import UserProfileForm


class UserProfileList(ListView):
    model = UserProfile


class UserProfileCreate(CreateView):
    model = UserProfile
    form_class = UserProfileForm


class UserProfileUpdate(UpdateView):
    model = UserProfile
    form_class = UserProfileForm


class UserProfileDelete(DeleteView):
    model = UserProfile
    success_url = reverse_lazy('profiles')

class UserProfileAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        # if not self.request.user.is_authenticated():
        #     return Country.objects.none()

        qs = UserProfile.objects.all()

        if self.q:
            qs = qs.filter(name__icontains=self.q)

        return qs

templates/user/userprofile_form.html
{% extends 'base.html' %}

{% block title %}
用户详情
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'basic:wordbooks' %}">字典列表</a></li>
{% endblock %}

{% block maincontent %}
<form id="warehouseForm" class="form-horizontal container" method="post" action="#">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if form.non_field_errors %}
            <ul style="list-style-type:none">
                {% for error in form.non_field_errors %}
                <li align="center" class="text-warning">
                    <h2>{{ error }}</h2>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="row">
                {% if form.name.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                        class="form-group col-md-6">{% endif %}
                        <label for="{{ form.name.id_for_label }}"
                            class="col-sm-4 control-label"><strong>姓名：</strong></label>
                        <div class="col-sm-8">
                            {{ form.name }}
                        </div>
                        {% if form.name.errors %}
                        <ul style="list-style-type:none">
                            {% for error in form.name.errors %}
                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>

                <div class="row">
                    {% if form.department.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                            class="form-group col-md-6">{% endif %}
                            <label for="{{ form.department.id_for_label }}"
                                class="col-sm-4 control-label"><strong>部门：</strong></label>
                            <div class="col-sm-8">
                                {{ form.department }}
                            </div>
                            {% if form.department.errors %}
                            <ul style="list-style-type:none">
                                {% for error in form.department.errors %}
                                <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                        {% if form.team.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                class="form-group col-md-6">{% endif %}
                                <label for="{{ form.team.id_for_label }}"
                                    class="col-sm-4 control-label"><strong>班组：</strong></label>
                                <div class="col-sm-8">
                                    {{ form.team }}
                                </div>
                                {% if form.team.errors %}
                                <ul style="list-style-type:none">
                                    {% for error in form.team.errors %}
                                    <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>

                        <div class="row">
                            {% if form.email.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                    class="form-group col-md-6">{% endif %}
                                    <label for="{{ form.email.id_for_label }}"
                                        class="col-sm-4 control-label"><strong>电子邮箱：</strong></label>
                                    <div class="col-sm-8">
                                        {{ form.user.email }}
                                    </div>
                                    {% if form.email.errors %}
                                    <ul style="list-style-type:none">
                                        {% for error in form.email.errors %}
                                        <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                {% if form.phone.errors %}<div class="form-group col-md-6 has-warning">{% else %}<div
                                        class="form-group col-md-6">{% endif %}
                                        <label for="{{ form.phone.id_for_label }}"
                                            class="col-sm-4 control-label">座机号码：</label>
                                        <div class="col-sm-8">
                                            {{ form.phone }}
                                        </div>
                                        {% if form.phone.errors %}
                                        <ul style="list-style-type:none">
                                            {% for error in form.phone.errors %}
                                            <li align="center" class="text-warning"><strong>{{ error }}</strong></li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="row">
                                    {% if form.mobile.errors %}<div class="form-group col-md-6 has-warning">{% else %}
                                        <div class="form-group col-md-6">{% endif %}
                                            <label for="{{ form.mobile.id_for_label }}"
                                                class="col-sm-4 control-label">手机号码：</label>
                                            <div class="col-sm-8">
                                                {{ form.mobile }}
                                            </div>
                                            {% if form.mobile.errors %}
                                            <ul style="list-style-type:none">
                                                {% for error in form.mobile.errors %}
                                                <li align="center" class="text-warning"><strong>{{ error }}</strong>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="row">
                                        {% if form.description.errors %}<div class="form-group col-md-6 has-warning">
                                            {% else %}<div class="form-group col-md-6">{% endif %}
                                                <label for="{{ form.description.id_for_label }}"
                                                    class="col-sm-4 control-label">备注：</label>
                                                <div class="col-sm-8">
                                                    {{ form.description }}
                                                </div>
                                                {% if form.description.errors %}
                                                <ul style="list-style-type:none">
                                                    {% for error in form.description.errors %}
                                                    <li align="center" class="text-warning"><strong>{{ error }}</strong>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-11">
                                        <button id="oper" type="submit" class="btn btn-primary">确认</button>
                                        <button type="button" class="btn btn-default">取消</button>
                                    </div>
                                </div>
                                {% if alert == 'T' %}
                                <div id="alert" class="alert alert-dismissable alert-success">员工信息修改成功！</div>
                                {% elif alert == 'F' %}
                                <div id="alert" class="alert alert-dismissable alert-warning">添加失败，稍后请重试</div>
                                {% else %}
                                <div id="alert"></div>
                                {% endif %}
</form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}

templates/user/userprofile_list.html
{% extends 'base.html' %}

{% block title %}
用户信息
{% endblock %}

{% block breadcrumb %}
<li id="orbit"><a href="{%url 'user:profiles' %}">用户列表</a></li>
{% endblock %}

{% block maincontent %}
<div id="data">
	<table id='dataTable' class='table table-bordered table-hover' cellspacing='0' width='100%'>
		<thead>
			<tr>
				<th>ID</th>
				<th>姓名</th>
				<th>部门</th>
				<th>分组</th>
				<th>邮箱</th>
				<th>电话</th>
				<th>操作</th>
			</tr>
		</thead>
		{% if object_list %}
		{% for u in object_list %}
		<tr>
			<th>{{ u.id }}</th>
			<th>{{ u.name }}</th>
			<th>{{ u.department.name }}</th>
			<th>{{ u.team.name }}</th>
			<th>{{ u.user.email }}</th>
			<th>{{ u.telephone }}</th>
			<th>
				<div class="hidden-sm hidden-xs btn-group">
					<a class="btn btn-xs btn-info" href="{% url 'user:edit_profile' u.id %}">
						<i class="ace-icon fa fa-pencil bigger-120"></i>
					</a>

					<a class="btn btn-xs btn-danger" href="{% url 'user:delete_profile' u.id %}">
						<i class="ace-icon fa fa-trash-o bigger-120"></i>
					</a>
				</div>
			</th>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<th colspan="7"><strong>There are no users present.</strong></th>
		</tr>
		{% endif %}
	</table>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/scripts/mainInit/warehouse.js"></script>
{% endblock %}